from typing import Any

class BashOperator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __rshift__(self, other: Any) -> Any: ...
    def __lshift__(self, other: Any) -> Any: ...
    def __rrshift__(self, other: Any) -> Any: ...
    def __rlshift__(self, other: Any) -> Any: ...
