repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: [--fix]
        types_or: [python, pyi]

      - id: ruff-format
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff-lint
        entry: uv run sqlfluff lint
        language: system
        files: ^dbt/olist_analytics/(analyses|macros|models|snapshots|tests)/.*\.sql$
